name: Nix

on: [push, pull_request, workflow_dispatch]

jobs:
  hyprlock:
    if: (github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork)
    uses: ./.github/workflows/nix-build.yml
    secrets: inherit

  test:
    if: (github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork)
    needs: hyprlock
    uses: ./.github/workflows/nix-test.yml
    secrets: inherit
